# Site settings
title: Zhuzhu's Blog
SEOTitle: Zhuzhu's 大平層 | Zhuzhu's Blog
header-img: img/home-bg.jpg
description: "關於海蠣與腦細胞、月亮與直角坐標系 | Zhuzhu，The world, Lifestyle, Explorations  | 這裡是Zhuzhu的海景大平層，一個放飛自我的地方。"
keyword: "博客, 個人網站, 記錄, ..."
url: "https://zhuzhu1999.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
email: "luotldudu@gmail.com"
#twitter_username: "twitteruser"
github_username: "zhuzhu1999"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
#weibo_username:     huxpro
#zhihu_username:     huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: zhuzhu-1

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-234381540-1'            # Format: UA-xxxxxx-xx
ga_domain: zhuzhu1999.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "兼墻頭草栽培家，互聯網衝浪金牌選手 <br> A fan of everything."
sidebar-avatar: /img/profile4.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    }   
]
